colmujeres = read.csv(file = "colmujeres.csv", header = TRUE, sep = ":", dec = ",")
View(colmujeres)
colhombres = read.csv(file = "colhombres.csv", header = TRUE, sep = ":", dec = ",")
View(colhombres)
attach(colhombres)
attach(colmujeres)
summary(colmujeres)
summary(colhombres)
range(colhombres)
# Varianza
var(colhombres)
var(colmujeres)
names(colhombres)
#histograma
hist(colh)
hist(colm)
#diagrama de caja
boxplot(colm)
boxplot(h)
#función densidad empírica
plot(density(colh))
plot(density(colm))
#gráficos de puntos
stripchart (colh, method="stack", pch=16)
stripchart (colm, method="stack", pch=16)
length(colh)
length(colm)
sd(colh)
sd(colm)
pnorm(240,mean=171,sd=30,lower.tail=F)
qnorm(0.85,mean=171,sd=30)
desv_tip <- sd(colh)
media <- mean(colh)
qnorm(0.85,media, desv_tip)
pnorm(6,mean=8,sd=3)
pnorm(6,mean=8,sd=3,lower.tail=F)
